@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package choonster.capability.foodfunk;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
